# Generated by Codex on 2026-04-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_excel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="direction",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
