# Generated by Django 5.2.3 on 2026-04-17 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_excel', '0003_profile_avatar_alter_payment_merchant_trans_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
    ]
