# Generated by Django 5.2.3 on 2026-04-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_excel', '0004_remove_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='department_head',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='faculty_dean',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
